spring:
  application:
    name: netflix-eureka-server
server:
  port: 8761

eureka:
  #instance:
    #hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #enableSelfPreservation: false